# DEVELOPMENT 
baseURL = "https://womensempowerment-lab-dev.netlify.com/" 

# PRODUCTION  
#baseURL = "http://womensempowerment.lab.mcgill.ca/" 

# DISABLE HUGO FROM GENERATING THE FOLLOWING 
disableKinds = ["RSS", "taxonomy", "taxonomyTerm", "sitemap"]

# LANGUAGE CODE
languageCode = "en-ca"
title = "Women's Economic Development Lab"

theme = "hugo-wed-lab"