# DEVELOPMENT ADDRESS
#baseURL = "https://womensempowerment-lab-dev.netlify.com/"

# PRODUCTION ADDRESS
baseURL = "https://womensempowerment.lab.mcgill.ca/"

# DISABLE HUGO FROM GENERATING THE FOLLOWING
disableKinds = ["RSS", "taxonomy", "taxonomyTerm", "sitemap"]

# LANGUAGE CODE
languageCode = "en-ca"

# BUILD THEME
theme = "hugo-wed-lab-v2"

# SITE SETTINGS
title = "Women's Empowerment in Development Lab at ISID"

# USER DEFINED SITE PARAMETERS
[params]
  description = "Run by the Institute for the Study of International Development. This Research-to-Practice Lab is bridging the gap between academics, practitioners and policy makers in Canada and globally on issues related to women's empowerment in developing countries."
